
[build]
  # Build command
  command = "npm run build"
  # Directory to publish
  publish = "dist"
  # Node version
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Build environment variables
  NODE_ENV = "production"
  VITE_SUPABASE_URL = "https://xokqnkvjpiygfxtmwmuu.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhva3Fua3ZqcGl5Z2Z4dG13bXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTY1OTYsImV4cCI6MjA2NDIzMjU5Nn0.yeW3mfg3Q30nYGR4SzClz5C57d7-1fBMgM7cslBxPOk"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/menu/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reservation"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/index.html"
  status = 200

# Form handling (if you want to use Netlify forms)
# [[plugins]]
#   package = "@netlify/plugin-form-submissions"
