
[build]
  # Build command with better error handling
  command = "npm ci && npm run build"
  # Directory to publish
  publish = "dist"

[build.environment]
  # Node version - using LTS
  NODE_VERSION = "20"
  NODE_ENV = "production"
  CI = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "noindex, nofollow"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific route redirects for better SEO
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/menu"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reservation"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/index.html"
  status = 200

# API redirects for Supabase
[[redirects]]
  from = "/api/*"
  to = "https://xokqnkvjpiygfxtmwmuu.supabase.co/functions/v1/:splat"
  status = 200

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
